steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/vrchat-analyzer/crawler', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/vrchat-analyzer/crawler']